theme="hugo_theme_robust"
baseURL = "http://material-hugo.com.s3-website-ap-northeast-1.amazonaws.com/"
languageCode = "ja"
title = "S3 test"

countryCode = "ja"

paginate = 9 # To specify a multiple of 3
copyright = "© 2015 Copyright Text"
hasCJKLanguage = "true"


[params]
  description = "Your Site Description" # optional
  twitter = "Your Twitter Name" # optional
  github = "Your Github Name" # optional
  facebook = "Your facebook Name" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
